name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Accept licenses
      run: yes | sdkmanager --licenses

    - name: Install NDK
      run: sdkmanager "ndk;29.0.13113456"

    - name: Set up local.properties
      run: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" >> local.properties
        echo "ndk.dir=$ANDROID_SDK_ROOT/ndk/29.0.13113456" >> local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace --no-daemon

    - name: Upload APK (optional)
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk

        - name: Build Debug APK
  run: ./gradlew assembleDebug --stacktrace --info --no-daemon
